/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "success-forest": "#10b981",
        "on-primary": "#ffffff",
        "primary-container": "#714b67",
        "surface": "#F8FAFC",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e2e8f0",
        "inverse-on-surface": "#f8fafc",
        "tertiary-fixed": "#d5eab4",
        "surface-tint": "#79526f",
        "tertiary-fixed-dim": "#b9ce9a",
        "surface-bright": "#f8f9ff",
        "tertiary": "#34451e",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#78d5db",
        "on-tertiary-container": "#c0d5a0",
        "secondary": "#0ea5e9",
        "inverse-surface": "#1e293b",
        "danger-brick": "#ef4444",
        "surface-base": "#F9FAFB",
        "on-background": "#0f172a",
        "background": "#F8FAFC",
        "outline": "#94a3b8",
        "on-tertiary": "#ffffff",
        "primary": "#714b67",
        "surface-container-high": "#f1f5f9",
        "on-tertiary-fixed": "#112000",
        "error": "#ef4444",
        "surface-container-low": "#FFFFFF",
        "on-primary-fixed": "#2f1029",
        "on-surface": "#0f172a",
        "on-secondary-container": "#0369a1",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#475569",
        "on-primary-container": "#f0bfe0",
        "primary-fixed-dim": "#e9b8d9",
        "on-tertiary-fixed-variant": "#3b4c24",
        "error-container": "#fee2e2",
        "on-secondary-fixed": "#002022",
        "secondary-container": "#e0f2fe",
        "on-secondary-fixed-variant": "#004f53",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#f1f5f9",
        "secondary-fixed": "#bae6fd",
        "on-primary-fixed-variant": "#5f3b56",
        "warning-amber": "#f59e0b",
        "surface-container": "#f8fafc",
        "on-error-container": "#991b1b",
        "primary-fixed": "#ffd7f1",
        "tertiary-container": "#4b5d33",
        "outline-variant": "#e2e8f0",
        "inverse-primary": "#e9b8d9",
        "odoo-teal": "#0d9488"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "32px",
        "sm": "8px",
        "gutter": "16px",
        "base": "4px",
        "md": "16px",
        "lg": "24px",
        "container-max": "1440px",
        "xs": "4px",
        "navbar-height": "64px",
        "sidebar-width": "260px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "mono-md": ["JetBrains Mono"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}]
      },
      boxShadow: {
        "soft": "0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        "soft-lg": "0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.05)"
      }
    },
  },
  plugins: [],
}
